<script src="/e_commorce/public/admin/assets/js/bootstrap.bundle.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.20.0/jquery.validate.min.js"></script>
<!-- <script src="/e_commorce/public/admin/assets/js/jquery.min.js"></script> -->
<script src="/e_commorce/public/admin/assets/plugins/metismenu/js/metisMenu.min.js"></script>
<script src="/e_commorce/public/admin/assets/js/app.js"></script>
<script src="/e_commorce/public/admin/assets/plugins/datatable/js/dataTables.bootstrap5.min.js"></script>
<script src="/e_commorce/public/admin/assets/plugins/datatable/js/jquery.dataTables.min.js"></script>
<script src="/e_commorce/public/admin/assets/js/pace.min.js"></script>
<script src="/e_commorce/public/admin/assets/js/table-datatable.js"></script>
<script src="/e_commorce/public/admin/assets/js/app.js"></script>
<script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
<script src="/e_commorce/public/admin/assets/js/yearpicker.js"></script>
<script src="/e_commorce/public/admin/assets/plugins/select2/js/select2.min.js"></script>
<script src="/e_commorce/public/admin/assets/js/form-select2.js"></script>